.create-merge table EventTag
(
    EventId:string,
    DateTimeUtc:datetime,
    CreatedBy:string,
    Tag:string,
    IsDeleted:bool
)

.alter table EventTag policy ingestiontime true

.alter-merge table EventTag policy retention softdelete = 1080d recoverability = disabled

.alter table EventTag policy ingestionbatching @'{"MaximumBatchingTimeSpan":"00:00:10", "MaximumNumberOfItems": 1, "MaximumRawDataSizeMB": 300}'